### ISSUE TITLE
PERFDATA : nagios status code

### ISSUE THREAD

**Issue by jbeaujour** [drewkerrigan/nagios-http-json#69]
Hello
Is that possible to add an optionnal perfdata for nagios status code ?
this would make it possible to monitor the validity of the probe in boolean mode: 0 for a CRITICAL status and 1 for an OK status.
availability can be calculated either on a threshold or on an anomaly in reading the URL
Thank's

**Comment by martialblog** [comment]
Hi, been thinking about this and as of now I don't think this change adds a lot of value.

I think having the status code as perfdata is redundant since the plugin already provides this data via its exit code. The plugin uses UNKNOWN (exit 3) to signal that something is not valid (e.g. HTTP or Parser Error). All other codes are used to signal valid handling of the JSON data.
