### ISSUE TITLE
Enhanced plugin output without critical information

### ISSUE THREAD

**Issue by K0nne** [drewkerrigan/nagios-http-json#83]
Hello,

is it possible to add a switch to enhance the plugin output with the pprint'ed json object?
I know this is already part of the debug switch, but we cant use -d, because we need to hide the used credentials, which are part of the -d output.

**Comment by martialblog** [comment]
Hi, we can have a look at it. 

Maybe it makes sense to hide credentials during the debug output. Would that cover your use case?

**Comment by K0nne** [comment]
We have tested a few scenarios. The used credentials can also be part of the header. 
I think its much safer to have a switch, which only shows the detailed json object.

**Comment by martialblog** [comment]
Been thinking about this. 

Since the `--debug` flag is boolean and meant for development or error debugging, it should print out all information to help with these tasks.

However, we could introduce a `-v` flag to increase the verbosity of the output. This flag could be used multiple times `-vv -v` to further increase the output. This would allow us to be more flexible in the future when we need to print out things that are valuable but not essential for debugging.

**Comment by K0nne** [comment]
Sounds good 👍🏻

**Comment by martialblog** [comment]
Implemented this feature here: https://github.com/drewkerrigan/nagios-http-json/pull/86

**Comment by martialblog** [comment]
@K0nne Does this cover the use case?

**Comment by K0nne** [comment]
It works perfect :) Big sorry for the delay!
